# Generated by Django 5.0.9 on 2024-09-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djanblog', '0003_post_description_post_published_post_updated_at_and_more'),
    ]

    operations = [
    ]
