# Generated by Django 5.0.9 on 2024-09-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djanblog', '0004_auto_20240920_1936'),
    ]

    operations = [
    ]
