# Generated by Django 5.0.9 on 2024-09-20 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djanblog', '0005_auto_20240920_1937'),
    ]

    operations = [
    ]
